update workflow yaml to include fail step

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -13,5 +13,10 @@ jobs:
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
+      - name: I will fail
+        run: |
+          echo "I will fail"
+          exit 1
+      
       - name: Say echo-goodbye
         run: echo "Goodbye"
